apiVersion: multitenancy.dev/v1alpha1
kind: Controller
metadata:
  name: example-controller
spec:
  tenancies:
    - namespace: foo
      charts:
        - chartName: deployment-example
          settings:
            - key: replicaCount
              value: "2"
        - chartName: statefulset-example
          releaseName: nginx
          settings:
            - key: replicas
              value: "3"
            - key: service.internalPort
              value: "8080"