kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multi-tenancy-operator
subjects:
- kind: ServiceAccount
  name: multi-tenancy-operator
  namespace: default
- kind: ServiceAccount
  name: multi-tenancy-operator
  namespace: foo
- kind: ServiceAccount
  name: multi-tenancy-operator
  namespace: bar
roleRef:
  kind: ClusterRole
  name: multi-tenancy-operator
  apiGroup: rbac.authorization.k8s.io
