apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-tenancy-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: multi-tenancy-operator
  template:
    metadata:
      labels:
        name: multi-tenancy-operator
    spec:
      serviceAccountName: multi-tenancy-operator
      containers:
        - name: multi-tenancy-operator
          # Replace this with the built image name
          image: ica10888/multi-tenancy-operator:v1.0.0
          command:
          - multi-tenancy-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: CHART_HOME
              value: "/root/chart"
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "multi-tenancy-operator"
          resources:
            limits:
              cpu: 1000m
              memory: 600Mi
            requests:
              cpu: 50m
              memory: 500Mi
          volumeMounts:
          - name: chart
            mountPath: /root/chart
      volumes:
        - name: chart
          persistentVolumeClaim:
            claimName: multi-tenancy

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: controllers.multitenancy.dev
spec:
  group: multitenancy.dev
  names:
    kind: Controller
    listKind: ControllerList
    plural: controllers
    singular: controller
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Controller is the Schema for the controllers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ControllerSpec defines the desired state of Controller
          properties:
            tenancies:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                properties:
                  charts:
                    items:
                      properties:
                        chartName:
                          type: string
                        releaseName:
                          type: string
                        settings:
                          items:
                            properties:
                              key:
                                type: string
                              value:
                                type: string
                            required:
                            - key
                            - value
                            type: object
                          type: array
                      required:
                      - chartName
                      - settings
                      type: object
                    type: array
                  namespace:
                    type: string
                required:
                - charts
                - namespace
                type: object
              type: array
          required:
          - tenancies
          type: object
        status:
          description: ControllerStatus defines the observed state of Controller
          properties:
            updatedTenancies:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                properties:
                  chartMessages:
                    items:
                      properties:
                        chartName:
                          type: string
                        errorMessage:
                          type: string
                        settingMap:
                          additionalProperties:
                            type: string
                          type: object
                      required:
                      - chartName
                      - settingMap
                      type: object
                    type: array
                  namespace:
                    type: string
                  podStatus:
                    items:
                      properties:
                        phase:
                          type: string
                        podName:
                          type: string
                      required:
                      - phase
                      - podName
                      type: object
                    type: array
                  replicationControllerStatus:
                    items:
                      properties:
                        apiVersion:
                          type: string
                        kind:
                          type: string
                        ready:
                          type: string
                        replicationControllerName:
                          type: string
                      required:
                      - apiVersion
                      - kind
                      - ready
                      - replicationControllerName
                      type: object
                    type: array
                required:
                - chartMessages
                - namespace
                - podStatus
                - replicationControllerStatus
                type: object
              type: array
          required:
          - updatedTenancies
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: multi-tenancy-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - multi-tenancy-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
- apiGroups:
  - multitenancy.dev
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multi-tenancy-operator
subjects:
- kind: ServiceAccount
  name: multi-tenancy-operator
  namespace: multi-tenancy
roleRef:
  kind: ClusterRole
  name: multi-tenancy-operator
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: multi-tenancy-operator
